added intel-mkl-64bit libs; delete --global-option="--disable-shared"
  Running setup.py install for pamqp: started
    Running setup.py install for pamqp: finished with status 'error'
    Complete output from command /builddir/venv/bin/python37 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-rpt5ergw/pamqp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" --disable-shared install --record /tmp/pip-record-w1la_o2l/install-record.txt --single-version-externally-managed --compile --install-headers /builddir/venv/include/site/python3.7/pamqp:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: option --disable-shared not recognized

    ----------------------------------------
/builddir/venv/lib64/python3.7/site-packages/pip/_internal/commands/install.py:207: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Command "/builddir/venv/bin/python37 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-rpt5ergw/pamqp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" --disable-shared install --record /tmp/pip-record-w1la_o2l/install-record.txt --single-version-externally-managed --compile --install-headers /builddir/venv/include/site/python3.7/pamqp" failed with error code 1 in /tmp/pip-install-rpt5ergw/pamqp/
error: Bad exit status from /var/tmp/rpm-tmp.hYxRnm (%prep)
    Bad exit status from /var/tmp/rpm-tmp.hYxRnm (%prep)