TRY to resolbe deps conflict with own builded py37-Cython --> Running transaction check ---> Package nlp-py-venv.x86_64 0:1.0.17-1.el7 will be installed --> Processing Dependency: /usr/bin/python3 for package: nlp-py-venv-1.0.17-1.el7.x86_64 --> Processing Dependency: libgfortran-ed201abd.so.3.0.0(GFORTRAN_1.0)(64bit) for package: nlp-py-venv-1.0.17-1.el7.x86_64 --> Processing Dependency: libgfortran-ed201abd.so.3.0.0(GFORTRAN_1.1)(64bit) for package: nlp-py-venv-1.0.17-1.el7.x86_64 --> Processing Dependency: libgomp-3300acd3.so.1.0.0(GOMP_1.0)(64bit) for package: nlp-py-venv-1.0.17-1.el7.x86_64 --> Processing Dependency: libgomp-3300acd3.so.1.0.0(OMP_1.0)(64bit) for package: nlp-py-venv-1.0.17-1.el7.x86_64 --> Processing Dependency: openblas-threads for package: nlp-py-venv-1.0.17-1.el7.x86_64 --> Running transaction check ---> Package nlp-py-venv.x86_64 0:1.0.17-1.el7 will be installed --> Processing Dependency: libgfortran-ed201abd.so.3.0.0(GFORTRAN_1.0)(64bit) for package: nlp-py-venv-1.0.17-1.el7.x86_64 --> Processing Dependency: libgfortran-ed201abd.so.3.0.0(GFORTRAN_1.1)(64bit) for package: nlp-py-venv-1.0.17-1.el7.x86_64 --> Processing Dependency: libgomp-3300acd3.so.1.0.0(GOMP_1.0)(64bit) for package: nlp-py-venv-1.0.17-1.el7.x86_64 --> Processing Dependency: libgomp-3300acd3.so.1.0.0(OMP_1.0)(64bit) for package: nlp-py-venv-1.0.17-1.el7.x86_64 ---> Package openblas-threads.x86_64 0:0.3.5-1.el7 will be installed ---> Package python3.x86_64 0:3.6.8-10.el7 will be installed --> Processing Dependency: python3-libs(x86-64) = 3.6.8-10.el7 for package: python3-3.6.8-10.el7.x86_64 --> Processing Dependency: python3-setuptools for package: python3-3.6.8-10.el7.x86_64 --> Processing Dependency: python3-pip for package: python3-3.6.8-10.el7.x86_64 --> Processing Dependency: libpython3.6m.so.1.0()(64bit) for package: python3-3.6.8-10.el7.x86_64 --> Running transaction check ---> Package nlp-py-venv.x86_64 0:1.0.17-1.el7 will be installed --> Processing Dependency: libgfortran-ed201abd.so.3.0.0(GFORTRAN_1.0)(64bit) for package: nlp-py-venv-1.0.17-1.el7.x86_64 --> Processing Dependency: libgfortran-ed201abd.so.3.0.0(GFORTRAN_1.1)(64bit) for package: nlp-py-venv-1.0.17-1.el7.x86_64 --> Processing Dependency: libgomp-3300acd3.so.1.0.0(GOMP_1.0)(64bit) for package: nlp-py-venv-1.0.17-1.el7.x86_64 --> Processing Dependency: libgomp-3300acd3.so.1.0.0(OMP_1.0)(64bit) for package: nlp-py-venv-1.0.17-1.el7.x86_64 ---> Package python3-libs.x86_64 0:3.6.8-10.el7 will be installed ---> Package python3-pip.noarch 0:9.0.3-5.el7 will be installed ---> Package python3-setuptools.noarch 0:39.2.0-10.el7 will be installed --> Finished Dependency Resolution Error: Package: nlp-py-venv-1.0.17-1.el7.x86_64 (copr:copr.internal.happify.com:vorona:stage-repo)            Requires: libgfortran-ed201abd.so.3.0.0(GFORTRAN_1.0)(64bit) Error: Package: nlp-py-venv-1.0.17-1.el7.x86_64 (copr:copr.internal.happify.com:vorona:stage-repo)            Requires: libgomp-3300acd3.so.1.0.0(GOMP_1.0)(64bit) Error: Package: nlp-py-venv-1.0.17-1.el7.x86_64 (copr:copr.internal.happify.com:vorona:stage-repo)            Requires: libgomp-3300acd3.so.1.0.0(OMP_1.0)(64bit) Error: Package: nlp-py-venv-1.0.17-1.el7.x86_64 (copr:copr.internal.happify.com:vorona:stage-repo)            Requires: libgfortran-ed201abd.so.3.0.0(GFORTRAN_1.1)(64bit)  You could try using --skip-broken to work around the problem  You could try running: rpm -Va --nofiles --nodigest
TRY to resolbe deps conflict with own builded py37-Cython
--> Running transaction check
---> Package nlp-py-venv.x86_64 0:1.0.17-1.el7 will be installed
--> Processing Dependency: /usr/bin/python3 for package: nlp-py-venv-1.0.17-1.el7.x86_64
--> Processing Dependency: libgfortran-ed201abd.so.3.0.0(GFORTRAN_1.0)(64bit) for package: nlp-py-venv-1.0.17-1.el7.x86_64
--> Processing Dependency: libgfortran-ed201abd.so.3.0.0(GFORTRAN_1.1)(64bit) for package: nlp-py-venv-1.0.17-1.el7.x86_64
--> Processing Dependency: libgomp-3300acd3.so.1.0.0(GOMP_1.0)(64bit) for package: nlp-py-venv-1.0.17-1.el7.x86_64
--> Processing Dependency: libgomp-3300acd3.so.1.0.0(OMP_1.0)(64bit) for package: nlp-py-venv-1.0.17-1.el7.x86_64
--> Processing Dependency: openblas-threads for package: nlp-py-venv-1.0.17-1.el7.x86_64
--> Running transaction check
---> Package nlp-py-venv.x86_64 0:1.0.17-1.el7 will be installed
--> Processing Dependency: libgfortran-ed201abd.so.3.0.0(GFORTRAN_1.0)(64bit) for package: nlp-py-venv-1.0.17-1.el7.x86_64
--> Processing Dependency: libgfortran-ed201abd.so.3.0.0(GFORTRAN_1.1)(64bit) for package: nlp-py-venv-1.0.17-1.el7.x86_64
--> Processing Dependency: libgomp-3300acd3.so.1.0.0(GOMP_1.0)(64bit) for package: nlp-py-venv-1.0.17-1.el7.x86_64
--> Processing Dependency: libgomp-3300acd3.so.1.0.0(OMP_1.0)(64bit) for package: nlp-py-venv-1.0.17-1.el7.x86_64
---> Package openblas-threads.x86_64 0:0.3.5-1.el7 will be installed
---> Package python3.x86_64 0:3.6.8-10.el7 will be installed
--> Processing Dependency: python3-libs(x86-64) = 3.6.8-10.el7 for package: python3-3.6.8-10.el7.x86_64
--> Processing Dependency: python3-setuptools for package: python3-3.6.8-10.el7.x86_64
--> Processing Dependency: python3-pip for package: python3-3.6.8-10.el7.x86_64
--> Processing Dependency: libpython3.6m.so.1.0()(64bit) for package: python3-3.6.8-10.el7.x86_64
--> Running transaction check
---> Package nlp-py-venv.x86_64 0:1.0.17-1.el7 will be installed
--> Processing Dependency: libgfortran-ed201abd.so.3.0.0(GFORTRAN_1.0)(64bit) for package: nlp-py-venv-1.0.17-1.el7.x86_64
--> Processing Dependency: libgfortran-ed201abd.so.3.0.0(GFORTRAN_1.1)(64bit) for package: nlp-py-venv-1.0.17-1.el7.x86_64
--> Processing Dependency: libgomp-3300acd3.so.1.0.0(GOMP_1.0)(64bit) for package: nlp-py-venv-1.0.17-1.el7.x86_64
--> Processing Dependency: libgomp-3300acd3.so.1.0.0(OMP_1.0)(64bit) for package: nlp-py-venv-1.0.17-1.el7.x86_64
---> Package python3-libs.x86_64 0:3.6.8-10.el7 will be installed
---> Package python3-pip.noarch 0:9.0.3-5.el7 will be installed
---> Package python3-setuptools.noarch 0:39.2.0-10.el7 will be installed
--> Finished Dependency Resolution
Error: Package: nlp-py-venv-1.0.17-1.el7.x86_64 (copr:copr.internal.happify.com:vorona:stage-repo)
           Requires: libgfortran-ed201abd.so.3.0.0(GFORTRAN_1.0)(64bit)
Error: Package: nlp-py-venv-1.0.17-1.el7.x86_64 (copr:copr.internal.happify.com:vorona:stage-repo)
           Requires: libgomp-3300acd3.so.1.0.0(GOMP_1.0)(64bit)
Error: Package: nlp-py-venv-1.0.17-1.el7.x86_64 (copr:copr.internal.happify.com:vorona:stage-repo)
           Requires: libgomp-3300acd3.so.1.0.0(OMP_1.0)(64bit)
Error: Package: nlp-py-venv-1.0.17-1.el7.x86_64 (copr:copr.internal.happify.com:vorona:stage-repo)
           Requires: libgfortran-ed201abd.so.3.0.0(GFORTRAN_1.1)(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest